# Generated by Django 4.0.4 on 2022-04-29 19:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import project.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField(validators=[project.common.validators.validate_only_percentage])),
                ('wind', models.IntegerField()),
                ('probability_for_rain', models.IntegerField(validators=[project.common.validators.validate_only_percentage])),
            ],
        ),
        migrations.CreateModel(
            name='ZodiacSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=11)),
                ('date', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=50)),
                ('ruling_planet', models.CharField(max_length=50)),
                ('personal_traits', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Razgrad', 'Razgrad')], max_length=7)),
                ('Weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weather')),
            ],
        ),
    ]
