# Generated by Django 4.0.4 on 2022-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Razgrad', 'Razgrad')], max_length=7),
        ),
    ]
