# Generated by Django 4.0.4 on 2022-04-29 07:49

from django.db import migrations, models
import project.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField(validators=[project.common.validators.validate_only_percentage])),
                ('wind', models.IntegerField()),
                ('probability_for_rain', models.IntegerField(validators=[project.common.validators.validate_only_percentage])),
            ],
        ),
    ]
