# Generated by Django 4.0.4 on 2022-04-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
            preserve_default=False,
        ),
    ]
