# Generated by Django 4.0.4 on 2022-04-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weather_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='Weather',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weather.weather'),
            preserve_default=False,
        ),
    ]
