# Generated by Django 4.0.4 on 2022-04-29 12:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_weather_city_city_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=100)),
                ('element', models.CharField(max_length=50)),
                ('ruling_planet', models.CharField(max_length=50)),
                ('personal_traits', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
