# Generated by Django 4.0.4 on 2022-04-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_alter_city_options_city_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='datetime',
            new_name='date',
        ),
    ]
