# Generated by Django 4.0.4 on 2022-04-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_alter_city_options_rename_datetime_city_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='date',
            new_name='date_joined',
        ),
    ]
