# Generated by Django 4.0.4 on 2022-04-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_alter_city_options_rename_date_city_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
