# Generated by Django 4.0.4 on 2022-04-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_alter_city_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='date_joined',
        ),
    ]
