# Generated by Django 4.0.4 on 2022-04-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Economics', 'Economics'), ('Coronavirus', 'Coronavirus'), ('Politics', 'Politics')], max_length=11)),
                ('image', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
