# Generated by Django 4.0.4 on 2022-04-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
    ]
