# Generated by Django 4.0.4 on 2022-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Economics', 'Economics'), ('Coronavirus', 'Coronavirus'), ('Politics', 'Politics'), ('Business', 'Business'), ('Entertainment', 'Entertainment')], max_length=13),
        ),
    ]
