# Generated by Django 4.0.4 on 2022-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_staff_alter_actnewsuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='actnewsuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
